### ISSUE TITLE
Origin of wordguesser data files?

### ISSUE THREAD

**Issue by gforcedev** [SquidDev/Cipher-Crackers#21]
I'm interested in writing an auto-spacer like the one included here, and I was wondering if:

 https://raw.githubusercontent.com/SquidDev/Cipher-Crackers/master/src/Cipher/Analysis/AutoSpace/2WordScores.txt

 and

 https://raw.githubusercontent.com/SquidDev/Cipher-Crackers/master/src/Cipher/Analysis/AutoSpace/1WordScores.txt

Are under the license in the readme or if they have some other origin which means that I am allowed to use them. (I use my cipher cracker for the national cipher challenge).

**Comment by SquidDev** [comment]
That particular code is a port of [Peter Norvig's code](http://norvig.com/ngrams/). It is MIT licensed so I can't stop you using it 😉. [Practical Cryptography](http://practicalcryptography.com/cryptanalysis/text-characterisation/word-statistics-fitness-measure/) also have a page this algorithm.

**Comment by gforcedev** [comment]
Thanks
